// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDTsRnce0NJrDOQ6f6QuqMbTMrNps-cxX0',
    appId: '1:526066959807:web:43ce0b1c5369029f33cd0a',
    messagingSenderId: '526066959807',
    projectId: 'wasset-project-68cc3',
    authDomain: 'wasset-project-68cc3.firebaseapp.com',
    storageBucket: 'wasset-project-68cc3.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC41GDFAGauiDwspUJrtRpuQr4w_Cg0cVk',
    appId: '1:526066959807:android:eb31b4cc45d1632c33cd0a',
    messagingSenderId: '526066959807',
    projectId: 'wasset-project-68cc3',
    storageBucket: 'wasset-project-68cc3.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBUnK_B0unZcpN8hRFzhUWaNzR5QwDAD7M',
    appId: '1:526066959807:ios:1d8bd61c7ad171f033cd0a',
    messagingSenderId: '526066959807',
    projectId: 'wasset-project-68cc3',
    storageBucket: 'wasset-project-68cc3.firebasestorage.app',
    iosBundleId: 'com.example.waseetProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBUnK_B0unZcpN8hRFzhUWaNzR5QwDAD7M',
    appId: '1:526066959807:ios:1d8bd61c7ad171f033cd0a',
    messagingSenderId: '526066959807',
    projectId: 'wasset-project-68cc3',
    storageBucket: 'wasset-project-68cc3.firebasestorage.app',
    iosBundleId: 'com.example.waseetProject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDTsRnce0NJrDOQ6f6QuqMbTMrNps-cxX0',
    appId: '1:526066959807:web:74254dfa44eee47b33cd0a',
    messagingSenderId: '526066959807',
    projectId: 'wasset-project-68cc3',
    authDomain: 'wasset-project-68cc3.firebaseapp.com',
    storageBucket: 'wasset-project-68cc3.firebasestorage.app',
  );
}
